import "./globals.css";
import { Navbar } from "@/components/sitewide/Navbar";
import { Header } from "@/components/sitewide/Header";
import { inter, normalFont } from "./fonts";

export const metadata = {
  title: "Todo App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${normalFont.className} bg-slate-800 text-slate-100 container mx-auto p-4`}
      >
        <Header />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
